services:
    lephare_admin_generator.command.admin_generator:
        class: "Lephare\Bundle\AdminGeneratorBundle\Command\GeneratorCommand"
        arguments:
            - "@kernel"
            - "@doctrine.orm.entity_manager"
            - { dest-path: "%kernel.root_dir%/Resources/metadata", kernel.root_dir: "%kernel.root_dir%" }
        tags:
            -  { name: console.command }
